### ISSUE TITLE
Disable vim select mode on opt/alt + left/right

### ISSUE THREAD

**Issue by valtism** [mattmc3/zephyr#1]
Hi there 👋🏻

Great project. Loving using it so far.

Just wondering if there is a simple way to disable the terminal from shifting into a `vim`-style select mode when I option+arrow to jump around the current text in the command.

**Comment by mattmc3** [comment]
The editor plugin should do this for you already: https://github.com/mattmc3/zephyr/blob/main/plugins/editor/editor.plugin.zsh

Are you sure you have Emacs keys set (`bindkey -e` or `setopt emacs`)? Or are you trying to use vi mode (`bindkey -v` or `setopt vi`), but then have alt+arrow work as a word movement combo?

**Comment by mattmc3** [comment]
Re-open if this didn't resolve the issue for you.

**Comment by valtism** [comment]
Super late to get around to this, but for posterity I solved this by running `antidote update`. I guess an older version had the vim behavior and the latest doesn't.
