### ISSUE TITLE
Editor plugin emacs-pound-insert issue

### ISSUE THREAD

**Issue by caden-parajuli** [mattmc3/zephyr#10]
Right now, when the editor plugin is loaded, the following error message shows:

> zsh-syntax-highlighting: unhandled ZLE widget 'emacs-pound-insert'
> zsh-syntax-highlighting: (This is sometimes caused by doing `bindkey <keys> emacs-pound-insert` without creating the 'emacs-pound-insert' widget with `zle -N` or `zle -C`.)

I think this is caused by commit `acdc0455164940b84693fd95703454a8d6dfeafb` changing the name of the function `pound-toggle` to `emacs-pound-insert` without changing the line (102) `zle -N pound-toggle` in [zephyr/blob/main/plugins/editor/editor.plugin.zsh ](https://github.com/mattmc3/zephyr/blob/762598575cea0c3d38053912a2dda4a5cffbe2a9/plugins/editor/editor.plugin.zsh#L102) to `zle -N emacs-pound-insert`. I have confirmed that doing so solves the issue.

**Comment by mattmc3** [comment]
Good catch. Pushed a fix.
