### ISSUE TITLE
mattmc3/zephyr/plugins/completion/completion.plugin.zsh:56: command not found: run-compinit

### ISSUE THREAD

**Issue by radiosilence** [mattmc3/zephyr#18]
All of a sudden I'm getting errors on my terminal on initialisation.

It seems to be that on completion.plugin.zsh, if manual mode is not enabled it's calling  a function called `run-compinit`.

In `completion/plugins/run-compinit`, the lines that wrap this in a function were commented out 7 months ago.

How is this supposed to work?

Thanks!

**Comment by mattmc3** [comment]
Hey @radiosilence! Thanks for the bug report. I use Zephyr as my daily driver, and I've not seen any issues like that recently. The commented `# function run-compinit {` might seem weird, but its normal for autoload functions, which don't require a function definition - the name of the file serves as the definition.

You wouldn't happen to have your dotfiles published somewhere, would you? If not, can you post the actual errors you're getting?

One thing to check - make sure you clear any completion cache you have with this command so you can start fresh:

```zsh
setopt extended_glob
rm -ri ${XDG_CACHE_HOME:-$HOME/.cache}/{zephyr,zsh}/zcompdump*(N)
```

**Comment by RobertBeilich** [comment]
I'm currently in the process of rebuilding my config and stumbled upon a similar error. Had not all of my `setop`s in yet, to reevaluate them, but zephyr requires `setop extended_glob` to be set.

**Comment by mattmc3** [comment]
Thank you @RobertBeilich. Great find. I pushed a commit that adds extended_glob in the bootstrap.zsh file since it's a critical Zsh option required for most anything Zephyr does.
