### ISSUE TITLE
Is it valid to load a part of Zephyr?

### ISSUE THREAD

**Issue by mel0n0** [mattmc3/zephyr#2]
Hello:-)

I recently tried using `Antidote` and `Zephyr` referencing your [dotfile](https://github.com/mattmc3/zdotdir). And there are two points that confused me.

First, is it valid to load only a certain part of Zephyr? For example, I just need `zephyr path:plugins/autosuggestions`.
Since the directory `functions` is not in fpath, will the following line be invalid?
https://github.com/mattmc3/zephyr/blob/f95c701dea829da1b95d8ce90438ff31c1a94388/plugins/autosuggestions/autosuggestions.plugin.zsh#L14

Another thing, when I used the plugin `fancy-ctrl-z`, I found that its bindkey did not work. I tried to search
bindkey by `$ bindkey | grep fancy`, but no results. Here is the related information：
```
# zsh --version
# zsh 5.9 (x86_64-apple-darwin20.6.0)

# .zsh_plugins.txt
ohmyzsh/ohmyzsh path:plugins/fancy-ctrl-z

# .zsh_plugins.zsh
fpath+=( /Users/me/.cache/antidote/ohmyzsh/ohmyzsh/plugins/fancy-ctrl-z )
source /Users/me/.cache/antidote/ohmyzsh/ohmyzsh/plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh
```

BTW, If I source `fancy-ctrl-z.plugin.zsh` manually, it works fine.

**Comment by mattmc3** [comment]
> Is it valid to load a part of Zephyr?

Yes, absolutely. In fact, that's the primary use case - to load only what you want.

> Since the directory functions is not in fpath, will the following line be invalid?

It should work fine. Antidote add your plugins to fpath, but even without antidote it shouldn't be a problem. If you are having an issue with it though, please describe further.

> Another thing, when I used the plugin fancy-ctrl-z, I found that its bindkey did not work

Is there a chance you have something else in your config that would reset your keybindings after you load fancy-ctrl-z? I tried a lot of different things to see if I could replicate the behavior you're describing, but I can't seem to.

```zsh
# from an interactive terminal, try this:
% source <(antidote bundle ohmyzsh/ohmyzsh path:plugins/fancy-ctrl-z)
% bindkey | grep fancy                                          
"^Z" fancy-ctrl-z
```

**Comment by mel0n0** [comment]
> It should work fine. Antidote adds your plugins to fpath, but even without antidote it shouldn't be a problem.

Thanks, I get it.

About `fancy-ctrl-z`, I also found out why it doesn't work according to your reply. This seems to be due to putting the below after `.zsh_plugins.zsh` is loaded in my zshrc.

```shell
# Choose your preferred keybindings.
bindkey -e   # Emacs keybindings
#bindkey -v  # Vi keybindings
```
