### ISSUE TITLE
completion not working correctly, returning unknown filename

### ISSUE THREAD

**Issue by jathek** [mattmc3/zephyr#20]
See below video. Tabbing to complete the filename "alias.cmd" somehow returns "alias.D" instead. The only plugin installed in antidote is `mattmc3/zephyr path:plugins/completion`. Happens in both current antidote versions from mattmc3 and getantidote.

https://github.com/mattmc3/zephyr @ https://github.com/mattmc3/zephyr/commit/c6c001dcf00eda378b2f21f37a2c53801b6fb20c
antidote version 1.9.5 ([90deef1](https://github.com/mattmc3/antidote/commit/90deef194d38206a0de63980b6147c3a83850055)) & antidote version 1.9.1 ([0e21ff3](https://github.com/getantidote/antidote/commit/0e21ff36c9ba218e6758664fb279a3080a5a9601))
zsh version: zsh 5.9 (x86_64-pc-msys)
OS: Microsoft Windows 10 Pro 10.0.19045
Terminal: Windows Terminal Preview 1.20.10572.0

<details>
<summary>.zshrc</summary>

```zsh
# Zsh options
setopt extended_glob

# Clone antidote if necessary.
[[ -d ${ZDOTDIR:-~}/.antidote ]] || git clone https://github.com/mattmc3/antidote ${ZDOTDIR:-~}/.antidote

# change antidote home directory - default on windows is %LocalAppData%/antidote
export ANTIDOTE_HOME=${ZDOTDIR:-~}/.antidote_home

# Set the name of the static .zsh plugins file antidote will generate.
zsh_plugins=${ZDOTDIR:-~}/.zsh_plugins.zsh

# Source zstyles you might use with antidote.
[[ -e ${ZDOTDIR:-~}/.zstyles.zsh ]] && source ${ZDOTDIR:-~}/.zstyles.zsh

# Ensure you have a .zsh_plugins.txt.zsh file where you can add plugins.
[[ -f ${zsh_plugins:r}.txt.zsh ]] || touch ${zsh_plugins:r}.txt.zsh

# Lazy-load antidote.
fpath+=(${ZDOTDIR:-~}/.antidote)
autoload -Uz $fpath[-1]/antidote

# Generate static file in a subshell when .zsh_plugins.txt.zsh is updated.
if [[ ! $zsh_plugins -nt ${zsh_plugins:r}.txt.zsh ]]; then
  (antidote bundle <${zsh_plugins:r}.txt.zsh >|$zsh_plugins)
fi

# Source your static plugins file.
source $zsh_plugins

PS1='%~ %% '
```
</details>
<details>
<summary>.zsh_plugins.txt.zsh</summary>

```zsh
mattmc3/zephyr path:plugins/completion
```
</details>

<details>
<summary>.zstyles</summary>

```zsh
# friendly plugin directories - no 'https-COLON--SLASH--SLASH-github.com-SLASH-'
zstyle ':antidote:bundle' use-friendly-names 'yes'
# change default zsh_plugins.txt name
zstyle ':antidote:bundle' file ${zsh_plugins:r}.txt.zsh
```
</details>

https://github.com/mattmc3/zephyr/assets/692914/e794f16f-a8e6-4595-88f7-a4a041653526

**Comment by jathek** [comment]
A bit of follow up: I tried switching to "[sorin-ionescu/prezto](https://github.com/sorin-ionescu/prezto) path:modules/completion" and it had the same issue.

**Comment by mattmc3** [comment]
Zephyr shamelessly uses Presto's completion zstyles as its base, and apparently there's a bug in this one:

```zsh
zstyle ':completion:*' matcher-list 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
```

 I've pushed a fix.

**Comment by mjolnir870** [comment]
Just updated but the same thing is happening.

**Comment by jathek** [comment]
I just updated to aef2b96 but the same thing seems to be happening
