### ISSUE TITLE
bootstrap.zsh seems to override variables

### ISSUE THREAD

**Issue by jwalton512** [mattmc3/zephyr#21]
It's quite possibly user error, but if so, I can't figure out what I'm doing wrong.

I have the following:

```bash
# .zprofile
...
export __zsh_config_dir=${ZDOTDIR:-$HOME}/.dotfiles/zsh

# .zsh_plugins.txt
...
mattmc3/zephyr path:plugins/confd
```

When I open a new terminal, `__zsh_config_dir` is updated to `/Users/jason/.config/zsh`
If I comment out the plugin, and reopen the terminal, `__zsh_config_dir` remains unchanged.

It seems like it's happening [here](https://github.com/mattmc3/zephyr/blob/f63ca450d8ba8eeb763e05daf6b1449a72e038aa/lib/bootstrap.zsh#L14)
My goal is to get the _confd_ plugin to look for configs in a different folder.

**Comment by mattmc3** [comment]
Thanks @jwalton512. Pushed a fix.
