### ISSUE TITLE
[color] command not found: is-macos

### ISSUE THREAD

**Issue by bustinbung** [mattmc3/zephyr#23]
On startup of a new shell, I get an error saying that zsh can't find the `is-macos` command in the color plugin. However, when I try to run `is-macos` in the prompt, it does work as expected.
```
/home/justin/.cache/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-mattmc3-SLASH-zephyr/plugins/color/color.plugin.zsh:61: command not found: is-macos

~/.config/zsh
❯ is-macos

❯
```

zsh 5.9
antidote 1.9.6

**Comment by mattmc3** [comment]
Great catch - I must have a different load order and always got is-macos from Zephyr's bootstrap. I pushed a fix. If you run `antidote update` you should be all set. Re-open if not.
