### ISSUE TITLE
zfunctions plugin does not read from ZFUNCDIR.

### ISSUE THREAD

**Issue by dvessel** [mattmc3/zephyr#24]
Setting `ZFUNCDIR` saves to the correct directory (funcsave) but it will not autoload. The default directory works fine but I don’t want to save it in ~/.config/zsh/functions.

Also, the readme makes no mention of fishcmds which is needed to use funcsave and funced.

Awesome project! Thanks for your time.

**Comment by dvessel** [comment]
Recent update broke it for my configuration. Setting ZFUNCDIR after `antidote load` clobbers it. It’s either setting it before loading or a deferred load from the plugin text file. I chose the latter. Not requiring fishcmds simplifies it. Thanks!

**Comment by mattmc3** [comment]
@dvessel - Thanks for your patience. I'm adding `clitests` to ensure that this remains stable and working.
