### ISSUE TITLE
Inclusion of zsh-completions submodule is unexpected

### ISSUE THREAD

**Issue by jeffqg** [mattmc3/zephyr#26]
The zsh-users/zsh-completions plugin was added as a submodule in https://github.com/mattmc3/zephyr/commit/6c62c8fc14c32dc0f283dbb3053d0f4e74283eb9. This runs counter to the FAQ from the README, "Why don't you also include popular plugins the way Prezto does (eg: zsh-autosuggestions, zsh-completions)?"

I don't know that this causes any problems, but it's a surprising discovery. IMO, the submodule should be removed from Zephyr and left to the user to pull in.

BTW, thanks for Zephyr and Antidote! My .zshrc is getting more understandable by the day.

**Comment by mattmc3** [comment]
You are correct. It's been removed.
