### ISSUE TITLE
Consider reverting brew sudo alias

### ISSUE THREAD

**Issue by mjsarfatti** [mattmc3/zephyr#30]
On Intel Macs the $HOMEBREW_PREFIX is, by default, `/usr/local`.

`/usr/local` is owned by the `root` user, and for security reasons it's a good idea to keep it like that.

This means that this [recent addition](https://github.com/mattmc3/zephyr/blob/7db75ce4e4f0f7b1b006ff4070dda77dcd081f3a/plugins/homebrew/homebrew.plugin.zsh#L70) in the **homebrew** plugin ends up always aliasing `brew` with `sudo`, even in single user systems.

(Also, brew suggests [avoiding `sudo` altogether](https://docs.brew.sh/FAQ#why-does-homebrew-say-sudo-is-bad))

Please consider reverting this change, or perhaps check for the owner of the `opt` subdirectory instead.

**Comment by mattmc3** [comment]
I pushed a commit so that 'brew' is only aliased on multi-user Apple Silicon.

**Comment by mattmc3** [comment]
I'm going to go ahead and close this issue, but feel free to re-open if there's anything else related to it that needs addressed.
