### ISSUE TITLE
`plugins/environment` breaking `code (VS Code CLI)

### ISSUE THREAD

**Issue by mrienstra** [mattmc3/zephyr#4]
macOS 12.3 Terminal.app, using default supplied ZSH.

`~/.zshrc`:
```
source ~/.zsh_plugins.zsh
```

`~/.zsh_plugins.txt`:
```
mattmc3/zephyr path:plugins/environment
```

Antidote installed with `brew install antidote`

After running:
```
source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
antidote bundle <~/.zsh_plugins.txt >~/.zsh_plugins.zsh
```

... `~/.zsh_plugins.zsh` contains:
```
fpath+=( /Users/foo/Library/Caches/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-mattmc3-SLASH-zephyr/plugins/environment )
source /Users/foo/Library/Caches/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-mattmc3-SLASH-zephyr/plugins/environment/environment.plugin.zsh
```

In a new Terminal session, attempting to use `code` to open a file, e.g. `code ~/.zshrc` launches a new instance of VS Code (instead of reusing the existing one, as it typically would), which shows the following error:
>### Unable to write program user data.
>A system error occurred (listen EACCES: permission denied /.xdg/vscode-352c82aa-1.72.2-main.sock)
>
>Please make sure the following directories are writeable:
>
>~/Library/Application Support/Code
>~/.vscode/extensions
>~/.xdg

https://github.com/mattmc3/zephyr/blob/11a376d/plugins/environment/environment.plugin.zsh sets `XDG_RUNTIME_DIR`, which is used by VS Code. The VS Code usage that appears in the error seems to be coming from here: https://github.com/microsoft/vscode/blob/3e40752/src/vs/base/parts/ipc/node/ipc.net.ts#L751-L773

Hmm, this looks like something that should be fixed in VS Code... 🤔

**Comment by nataliafonseca** [comment]
Creating `$HOME/.xdg` directory fixed this for me. Checking if the each of the set XDG base dirs exist and, if not, creating them, might be interesting within the plugin.

**Comment by mattmc3** [comment]
Thanks @nataliafonseca. I added `mkdir -p` commands for the XDG dirs.
