### ISSUE TITLE
How to change cursor style

### ISSUE THREAD

**Issue by valtism** [mattmc3/zephyr#5]
Hey there 👋🏻

Just wondering how I can configure the cursor style. It seems that this plugin sets it to a block style which overrides the emulator's style. Is there a way to configure it back to a line instead of a block?

Thanks for this great plugin and everything around it.

**Comment by mattmc3** [comment]
Hey @valtism - sorry for the long delay getting back to you. Thank you for the kind words. I've really enjoyed working on this project and pulling in the best stuff from places like OMZ, Prezto, and Zsh-Utils to make something simple and fast.

Configuring the cursor style in Zsh can be a bit tricky. I should probably add something to Zephyr to let you pick the style you want. In the mean time, try something like this in your config and see if it suits you.

```zsh
function update-cursor-style {
  [[ $TERM = xterm* ]] || return

  local cur_block=$'\e[2 q'
  local cur_line=$'\e[6 q'

  if bindkey -lL main | grep viins > /dev/null; then
    # vi-mode
    case $KEYMAP in
      vicmd)      printf $cur_block;;
      viins|main) printf $cur_line;;
    esac
  else
    # emacs mode
    printf $cur_line
  fi
}
zle -N update-cursor-style

function zle-line-init {
  (( ! $+terminfo[smkx] )) || echoti smkx
  zle update-cursor-style
}
zle -N zle-line-init
```
