### ISSUE TITLE
functions/man: Mixing `env` and `command` doesn't work

### ISSUE THREAD

**Issue by softmoth** [mattmc3/zephyr#6]
Man command doesn't work presently:

```$ man ls
env: ‘command’: No such file or directory
```

The reason is commit df3bf52, which does `env ... command man`. But `command` is a shell built-in, and env can't use it. Better to use `/usr/bin/man` which should be the right path everywhere, I guess.

**Comment by mattmc3** [comment]
I'm not sure why I was using env other than because it was used here: https://github.com/ael-code/zsh-colored-man-pages/blob/master/colored-man-pages.plugin.zsh

Removing the dependency on `env`, which apparently works differently on macOS than elsewhere, hopefully resolves this for you.
